services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - .env
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 1s
      timeout: 4s
      retries: 3
    volumes:
      - data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    restart: always

  backend:
    # build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    #  args:
    #    some-arg: 1
    container_name: backend
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      dockerfile: ./Dockerfiles/backend-dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
#    volumes:
#      - logs:/app/logs
#      - ./backend:/app
#      - /app/node_modules
#    env_file:
#      - ./env/backend.env


  frontend:
    container_name: frontend
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      dockerfile: ./Dockerfiles/frontend-dev.Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
#      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  data: