services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1s
      interval: 1s
      timeout: 4s
      retries: 3
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:3306"

  backend:
    # build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    #  args:
    #    some-arg: 1
    build:
      context: .
      dockerfile: ./Dockerfiles/backend-dev.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
#    volumes:
#      - logs:/app/logs
#      - ./backend:/app
#      - /app/node_modules
#    env_file:
#      - ./env/backend.env


  frontend:
    build:
      context: .
      dockerfile: ./Dockerfiles/frontend-dev.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
#    volumes:
#      - ./frontend/src:/app/src
    depends_on:
      - backend

#volumes:
#  data:
#  logs:
