services:

  backend:
    # build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    #  args:
    #    some-arg: 1
    build:
      context: .
      dockerfile: ./Dockerfiles/backend.Dockerfile
    ports:
      - "8080:8080"
#    volumes:
#      - logs:/app/logs
#      - ./backend:/app
#      - /app/node_modules
#    env_file:
#      - ./env/backend.env

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfiles/frontend.Dockerfile
    ports:
      - "8000:8000"
#    volumes:
#      - ./frontend/src:/app/src
    depends_on:
      - backend

#volumes:
#  data:
#  logs:

